name: CI
on:
  push:
    branches: [ develop ]
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ develop ]

env:
  FORCE_COLOR: 1
  EARTHLY_MAX_REMOTE_CACHE: "true"
  EARTHLY_VERBOSE: "true"

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: eniblock/build/actions/init@main
      id: init
      with:
        dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build xdev-lib
      run: |
         earthly --strict --push +build-xdev-lib \
         --cache-from xdevci/frontlibrary:cache-develop \
         --remote-cache xdevci/frontlibrary:cache-${{ github.ref_name }}
    - name: Build eniblock
      run: |
         earthly --strict --push +build-xdev-lib \
         --cache-from xdevci/frontlibrary:cache-develop \
         --remote-cache xdevci/frontlibrary:cache-${{ github.ref_name }}
